let cv=[
  "",
  "",
  "",
  "<font color='red'>LOÏC OBERLE</font>",
  "",
  "",
  "<!-- <img src=\"./ressources/images/chat.jpg\"</img> -->",
  "",
  "----------------------------------",
  "<font color='blue'>Formations:</font>",
  "",
  "2016-2018",
  "DUT Informatique à l'IUT Nancy Charlemagne",
  "",
  "",
  "---------------------------------",
  "<font color='blue'>Expériences professionnelles:</font>",
  "",
  "Stage de fin d'étude de DUT dans la société Partenaire Informatique",
  "Durée: 6 mois",
  "Rôle: analyste programmeur",
  "",
  "--------------------------------",
  "<font color='blue'>Compétences en informatique:</font>",
  "",
  "-Java",
  "-Javascript",
  "-PHP",
  "-C",
  "-SQL",
  "-Windev",
  "-Webdev",
  "",
  "--------------------------------",
  "<font color='blue'>Compétences en langue:</font>",
  "",
  "Anglais: Lut,écrit,parlé (score de 990 au TOEIC)",
  "",
  "Allemand: débutant",
  "",
  "--------------------------------",
  "<font color='blue'>Loisirs:</font>",
  "",
  "-Programmation",
  "-Lecture",
  "-Marche à pied",
  "",
  "-------------------------------",
  "<font color='blue'>Contact:</font>",
  "",
  "<font color='red'>Adresse Mail:</font> loicoberle@neuf.fr",
  "<font color='green'>Facebook:</font> Loïc Oberle",
  "<font color='cyan'>Twitter:</font> @_snauman",
  "<font color='green'>LinkedIn:</font> Loïc Oberle"
];
